spring:
  datasource:
    url: jdbc:h2:mem:proddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: lennon
    password: abc123
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
  flyway:
    url: jdbc:h2:mem:proddb;DB_CLOSE_DELAY=-1
    user: lennon
    password: abc123
    locations: db/migration