version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: tarefas_db
    environment:
      POSTGRES_USER: lennon
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: tarefas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
